Repository percona/pmm, pull requests merged in 2022-10, with the labels that each got.

#1273 PMM-10445 Replace local reviewdog with github action version
  .github/workflows/common.yml
Labels: enhancement, CI, hacktoberfest

#1299 Fix stats_collection field migration test
  managed/models/database_test.go
Labels: hacktoberfest

#1316 ci: change percona-platform to actions
  .github/workflows/admin.yml
  .github/workflows/agent.yml
  .github/workflows/api.yml
  .github/workflows/clean.yml
  .github/workflows/common.yml
  .github/workflows/doc.yml
  .github/workflows/managed.yml
Labels: enhancement, CI, hacktoberfest, hacktoberfest-accepted
