Repository percona/pmm, pull requests merged in 2023-06, with the labels that each got.

#2226 PMM-12189 automate updates of docker readme
  .github/workflows/dockerhub-readme.yml
  build/docker/rpmbuild/Dockerfile.el9
  build/docker/server/README.md
Labels: CI, documentation, docker

#2250 Improved sed
  scripts/authfix.sh
Labels: enhancement

#1811 PMM-10391-clickhouse-ordinary-to-atomic
  qan-api2/db.go
  qan-api2/main.go
Labels: in QA
